### ISSUE TITLE
Home page context 

### ISSUE THREAD

**Issue by kayode96-max** [Vedantjn/smooth-hire#11]
The home page should include documentation on what the app does 
There should be a clear representation of buttons to sign up or log in as company or applicant 
There should also be an about page that can be navigated to from the dashboard detailing the application processes and workflow of the app

I'll be glad if I can be assigned to fix this issues

**Comment by Vedantjn** [comment]
Go with it @kayode96-max

**Comment by kayode96-max** [comment]
@Vedantjn I'm through with this 
I have also added the new header and footer to all pages before login
Kindly merge the pull request

**Comment by kayode96-max** [comment]
@Vedantjn 
Are you there?
Is there an adjustment?
