### ISSUE TITLE
 Implement Company Registration and Login

### ISSUE THREAD

**Issue by Vedantjn** [Vedantjn/smooth-hire#3]
Add functionality for companies to register and log in to the Easy Apply platform. This will involve:

Company Registration:
Create a registration form where companies can input their details (company name, email, password, etc.).
Validate the credentials before storing them in the database securely.
Company Login:
Implement a login system that allows companies to log in using their registered email and password.
Once logged in, redirect them to their company dashboard.

**Comment by varunvaatsalya** [comment]
I can make it please assign it to me !

**Comment by Vedantjn** [comment]
Great, also go with the codebase first. I'm assigning this to you @varunvaatsalya .

**Comment by Vedantjn** [comment]
Assigning this to you, all the best @varunvaatsalya

**Comment by Vedantjn** [comment]
The issue has been resolved.
